Testing
nicolasmarino99/Tic-tac-toe-testing pull request #1
Opened 2019-08-27 21:27 UTC by MauricioRobayo

2019-08-27 23:54 UTC, bellom requested changes
Hi Team,
Great work guys but we need to work on some few things having thumps up...
Kindly work on my comments.
_Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you_

2019-08-27 23:54 UTC, bellom commented on spec/board_spec.rb
> +    it 'returns true for a winning row' do
kindly leave an empty line between `it` block, check an example below;
#Bad 
```
 it 'should return true when the third row of the board is filled with the same symbol' do
      game.board_game.board = %w[1 2 3 4 5 6 O O O]
      expect(game.win?).to eql(true)    
 end
  it 'should return true when the first column of the board is filled with the same symbol' do
      game.board_game.board = %w[O 2 3 O 5 6 O 8 9]
      expect(game.win?).to eql(true)
  end
```

#Good
```
 it 'should return true when the third row of the board is filled with the same symbol' do
      game.board_game.board = %w[1 2 3 4 5 6 O O O]
      expect(game.win?).to eql(true)
  end

  it 'should return true when the first column of the board is filled with the same symbol' do
      game.board_game.board = %w[O 2 3 O 5 6 O 8 9]
      expect(game.win?).to eql(true)
  end
```
Kindly apply for the rest of the `it` blocks.
check the [link](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-between-describes) for more info........

2019-08-27 23:54 UTC, bellom commented on lib/board.rb
Always run and test your code before submitting for review..
i try to run your code but threw an weird error, see error below;
```
**Failure/Error: require 'paint'

LoadError:
  cannot load such file -- paint**
```
i guess you're trying to require `paint` for styling which obviously not working.

2019-08-28 23:26 UTC, maelfosso requested changes
Hello,

Really nice improvement in your code. That's great !!
Please, is there no test for `Game.rb` ?

Kindly check the comment below.
Make the corresponding changes and re-submit a new code review request.

Thanks.

2019-08-28 23:26 UTC, maelfosso commented on spec/board_spec.rb
> +  end
```ruby
$ rspec spec/board_spec.rb 
....F

Failures:

  1) Board#to_s return string representing the board
     Failure/Error: expect(board.to_s).to eql(expected_string)
     
       expected: " \e[37m1\e[0m | \e[37m2\e[0m | \e[37m3\e[0m\n---+---+---\n \e[37m4\e[0m | \e[37m5\e[0m | \e[37m6\e[0m\n---+---+---\n \e[37m7\e[0m | \e[37m8\e[0m | \e[37m9\e[0m"
            got: " 1 | 2 | 3\n---+---+---\n 4 | 5 | 6\n---+---+---\n 7 | 8 | 9"
     
       (compared using eql?)
     
       Diff:
       
       
       @@ -1,6 +1,6 @@
       - 1 | 2 | 3
       + 1 | 2 | 3
        ---+---+---
       - 4 | 5 | 6
       + 4 | 5 | 6
        ---+---+---
       - 7 | 8 | 9
       + 7 | 8 | 9
       
     # ./spec/board_spec.rb:40:in `block (3 levels) in <top (required)>'

Finished in 0.01314 seconds (files took 0.07261 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/board_spec.rb:36 # Board#to_s return string representing the board
```

2019-08-29 16:19 UTC, bolah2009 requested changes
# Awesome Job Team

## Good job with the required changes too. 

Before giving a :+1: let's add one more test (See the comment below). :blush: 

I comment out the whole method and the test is still passing. :open_mouth: 

https://github.com/nicolasmarino99/Tic-tac-toe-testing/blob/dc5801cf7089f5868b94d8b46372bddf0bc0ce15/lib/player.rb#L14-L28

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-29 16:19 UTC, bolah2009 commented on spec/player_spec.rb
> +describe Player do
#### `REQUIRED`

Let's add `#get_position` test too. :+1:

2019-08-29 17:13 UTC, MauricioRobayo commented on spec/player_spec.rb
> +describe Player do
Thanks for the feedback!

We refactor `#get_position` to use helper methods so we could have better test cases and more readable code.

We were not sure on how to test user input so that's why we didn't test that method before, but we were able to figure it out.

Very helpful feedback, thank you!

2019-08-29 17:31 UTC, bellom commented
## Currently reviewing this PR

2019-08-29 17:56 UTC, bellom approved these changes
Hi Team, 
Great work making all the necessary corrections from the previous review.
## Congratulation :+1:

2019-08-29 19:04 UTC, merged